name: Atualizar dados diariamente

on:
  schedule:
    - cron: '0 11 * * *'  # 08h Brasília
    - cron: '0 12 * * *'  # 09h Brasília
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  executa-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests openpyxl

    - name: Rodar script Python
      run: python unificado.py
